import Head from "next/head";
import { useState } from 'react';
import Papa from 'papaparse';

export default function Home() {

  // Criar a variável para receber os dados
  const [dados, setDados] = useState([]);

  // Função para ler os dados do CSV
  const lerDadosArquivo = (e) => {

    // Receber o arquivo do formulário
    const arquivo = e.target.files[0];

    // Verificar se existe o arquivo
    if(arquivo){

      // Usar a biblioteca para analisar o arquivo
      Papa.parse(arquivo, {
      //Papa.parse('arquivo_inexistente.csv', {
        //download: true,
        header: true, // Define se a primeira linha do CSV é um cabeçalho
        dynamicTyping: true, // Converter automaticamente números e datas
        complete: (result) => { // Acessar complete após realizar a leitura do CSV
          console.log(result.data);
          setDados(result.data);
        },
        error: (error) => {
          alert('Erro ao analisar o CSV: ', error.message);
        }
      })
    }
  }

  return (
    <>
      <Head>
        <title>CSV REACT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <h3>Ler dados do arquivo CSV</h3>

        <label>Arquivo: </label>
        <input type='file' accept='.csv' onChange={lerDadosArquivo}/><br /><br />

        <table>
          <thead>
            <tr>
                <th>Telefone</th>
                <th>CPF</th>
                <th>Nome</th>
                <th>E-mail</th>
            </tr>
          </thead>
          <tbody>
            {/* Percorrer a listas de registros */}
            {dados.map((row, index) => (
              <tr key={index}>
                <td>{row.telefone}</td>
                <td>{row.cpf}</td>
                <td>{row.nome}</td>
                <td>{row.email}</td>
              </tr>
            ))}
          </tbody>
        </table>

      </main>
    </>
  );
}
